### ISSUE TITLE
allow users to add supports arbitrarily

### ISSUE THREAD

**Issue by EmilPoulsen** [EmilPoulsen/Frixel#12]
instead of automatically assuming lower nodes to be supports, we could let the user define supports wherever they want in the model. this would be very powerful cause then you could suddenly explore more designs than just typical towers/buildings.

we shouldn't delete the `auto lower nodes` functionality however, but maybe it can become an option through a button similar to `BraceAll`.

**Comment by lelandjobson** [comment]
Good idea

**Comment by lelandjobson** [comment]
![image](https://user-images.githubusercontent.com/17731181/43113336-fe58fb76-8ec7-11e8-9d67-6b4ef154425c.png)

**Comment by EmilPoulsen** [comment]
awesome
