### ISSUE TITLE
add deflection animation

### ISSUE THREAD

**Issue by EmilPoulsen** [EmilPoulsen/Frixel#16]
create option to run animation of the tranformation between undeflected and deflected shape. would be the same effect as dragging the slider back and forth

**Comment by lelandjobson** [comment]
Not bad to implement. Used WPF built in animations.

https://raw.githubusercontent.com/EmilPoulsen/Frixel/master/doc/Frixel_Play.gif

**Comment by EmilPoulsen** [comment]
nice! ur killing it
